# Setup
title:               Josh Bradshaw
tagline:             'A Jekyll theme'
description:         # left intentionally blank
url:                 https://joshbradshaw.me
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Josh Bradshaw
  url:               # left intentionally blank
  email:             contact@joshbradshaw.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-63195004-1
