# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Joyful Misadventures'
tagline:          'A collection of musings.'
description:      'A collection of musings.'

author:
  name:           'Josh Bradshaw'

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/JoshBradshaw

docs:
  resume:         /docs/Josh-Bradshaw-Resume.pdf
